name: CI for API

on:
  push:
    paths:
      - "api/**"
  pull_request:
    paths:
      - "api/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./api

jobs:
  Lint-Check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Run lint:check
        run: npm run lint:check

  Type-Check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Run type:check
        run: npm run type:check

  Test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build
